[package]
name = "api"
version = "0.1.0"
authors = ["sonmezonur"]

[dependencies]
initials = { git = "https://github.com/sonmezonur/initials.rs" }
actix = "0.7.4"
actix-web = "0.7.8"
serde = "1.0"
serde_derive = "1.0"
